### ISSUE TITLE
Windows installer failed to build

### ISSUE THREAD

**Issue by mtdukes** [nprapps/portland2#43]
The Mac build worked like a charm, but the Windows build failed here:

`electron-builder electron/Lunchbox-win32-ia32 --platform=win --config=packager-config.json`

I'm on OSX with all the other prerequisites. Here's the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'pack' ]
2 info using npm@1.5.0-alpha-1
3 info using node@v0.10.28
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prepack', 'pack', 'postpack' ]
6 info prepack app-template@1.0.0
7 info pack app-template@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info app-template@1.0.0 Failed to exec pack script
10 error app-template@1.0.0 pack: `npm run build && npm run pack:osx && npm run pack:win`
10 error Exit status 1
11 error Failed at the app-template@1.0.0 pack script.
11 error This is most likely a problem with the app-template package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     npm run build && npm run pack:osx && npm run pack:win
11 error You can get their info via:
11 error     npm owner ls app-template
11 error There is likely additional logging output above.
12 error System Darwin 14.0.0
13 error command "node" "/usr/local/bin/npm" "run-script" "pack"
14 error cwd /Users/mtdukes/Documents/development/lunchbox
15 error node -v v0.10.28
16 error npm -v 1.5.0-alpha-1
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

Any ideas?

**Comment by mtdukes** [comment]
OK, @TylerFisher pointed out my node was out of date and that I didn't run

`brew install wine makensis`

So did both of those. Now neither installer will build. Seems to fail in several places. Here's the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'pack' ]
2 info using npm@2.13.2
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prepack', 'pack', 'postpack' ]
6 info prepack app-template@1.0.0
7 info pack app-template@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info app-template@1.0.0 Failed to exec pack script
10 verbose stack Error: app-template@1.0.0 pack: `npm run build && npm run pack:osx && npm run pack:win`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid app-template@1.0.0
12 verbose cwd /Users/mtdukes/Documents/development/lunchbox
13 error Darwin 14.0.0
14 error argv "node" "/usr/local/bin/npm" "run-script" "pack"
15 error node v0.12.7
16 error npm  v2.13.2
17 error code ELIFECYCLE
18 error app-template@1.0.0 pack: `npm run build && npm run pack:osx && npm run pack:win`
18 error Exit status 1
19 error Failed at the app-template@1.0.0 pack script 'npm run build && npm run pack:osx && npm run pack:win'.
19 error This is most likely a problem with the app-template package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run build && npm run pack:osx && npm run pack:win
19 error You can get their info via:
19 error     npm owner ls app-template
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by mtdukes** [comment]
Nevermind! Started over after updating everything and it works great.

**Comment by nithinkashyapn** [comment]
Hey, I am trying to build electron apps of lunchbox on Ubuntu; I did install `wine` and `nsis` but still get the following output.

```
Error: Invalid platform.
    at Object.build (/home/kashyap/Documents/lunchbox/node_modules/electron-builder/lib/osx.js:28:24)
    at Object.build (/home/kashyap/Documents/lunchbox/node_modules/electron-builder/index.js:73:42)
    at Object.<anonymous> (/home/kashyap/Documents/lunchbox/node_modules/electron-builder/cli.js:26:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lunchbox@1.0.0 pack:osx: `electron-builder electron/Lunchbox-darwin-x64/Lunchbox.app --platform=osx --config=packager-config.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lunchbox@1.0.0 pack:osx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
