### ISSUE TITLE
Trouble deploying to s3

### ISSUE THREAD

**Issue by pattiereaves** [nprapps/portland2#52]
Thank you for this awesome app!

I followed the guide and I want to deploy to S3, but when I run

```
$ fab production master deploy
```

I get this error:

```
Traceback (most recent call last):
  File "/Users/preaves/.virtualenvs/lunchbox/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/Users/preaves/.virtualenvs/lunchbox/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/preaves/.virtualenvs/lunchbox/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Library/WebServer/Documents/lunchbox/lunchbox/fabfile/__init__.py", line 125, in deploy
    if app_config.DEPLOY_TO_SERVERS:
AttributeError: 'module' object has no attribute 'DEPLOY_TO_SERVERS'
```

Ideas what I'm doing wrong?

(Sorry if this is a total n00b question)

**Comment by TylerFisher** [comment]
Looks like you have an old version of the code. If you copy all of `fabfile/__init__.py` from this repo and paste it into the same file on your local machine so it gets into your fork, it should work.

**Comment by pattiereaves** [comment]
I just came here to comment that I did a git pull and it fixed it. Sorry! :)
